HDF5 "file_space.h5" {
SUPER_BLOCK {
   SUPERBLOCK_VERSION 2
   FREELIST_VERSION 0
   SYMBOLTABLE_VERSION 0
   OBJECTHEADER_VERSION 0
   OFFSET_SIZE 8
   LENGTH_SIZE 8
   BTREE_RANK 16
   BTREE_LEAF 4
   ISTORE_K 32
   FILE_SPACE_STRATEGY H5F_FILE_SPACE_AGGR_VFD
   FREE_SPACE_THRESHOLD 10
   USER_BLOCK {
      USERBLOCK_SIZE 0
   }
}
GROUP "/" {
}
}
