HDF5 "tfcontents1.h5" {
SUPER_BLOCK {
   SUPERBLOCK_VERSION 0
   FREELIST_VERSION 0
   SYMBOLTABLE_VERSION 0
   OBJECTHEADER_VERSION 0
   OFFSET_SIZE 8
   LENGTH_SIZE 8
   BTREE_RANK 16
   BTREE_LEAF 4
   ISTORE_K 32
   FILE_SPACE_STRATEGY H5F_FILE_SPACE_ALL
   FREE_SPACE_THRESHOLD 1
   USER_BLOCK {
      USERBLOCK_SIZE 0
   }
}
DATASET "dset" {
   DATATYPE  H5T_STD_I32BE
   DATASPACE  SIMPLE { ( 4 ) / ( 4 ) }
}
}
