/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the files COPYING and Copyright.html.  COPYING can be found at the root   *
 * of the source code distribution tree; Copyright.html can be found at the  *
 * root level of an installed copy of the electronic HDF5 document set and   *
 * is linked from the top-level documents page.  It can also be found at     *
 * http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *
 * access to either file, you may request a copy from help@hdfgroup.org.     *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Apr  8, 2015
 *			Sergey Zyrianov <sz@sz-box>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"      SUMMARY OF THE HDF5 CONFIGURATION\n"
	"      =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.9.178\n"
	"                  Configured on: \n"
	"                  Configured by: Unix Makefiles\n"
	"                 Configure mode: CMAKE 2.8.12.2\n"
	"                    Host system: Linux-3.13.0-24-generic\n"
	"              Uname information: Linux\n"
	"                       Byte sex: little-endian\n"
	"                      Libraries: \n"
	"             Installation point: /home/sz/deep/rnnlib_openblas/install\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"               Compilation Mode: \n"
	"                     C Compiler: /usr/bin/cc\n"
	"                         CFLAGS:   -std=c99 -fomit-frame-pointer -finline-functions -fno-common -Wextra -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -fmessage-length=0\n"
	"                      H5_CFLAGS: \n"
	"                      AM_CFLAGS: \n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: \n"
	"                    AM_CPPFLAGS: \n"
	"               Shared Libraries: NO\n"
	"               Static Libraries: YES\n"
	"  Statically Linked Executables: OFF\n"
	"                        LDFLAGS:  \n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: m;dl\n"
	"                       Archiver: /usr/bin/ar\n"
	"                         Ranlib: /usr/bin/ranlib\n"
	"              Debugged Packages: \n"
	"                    API Tracing: OFF\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                        Fortran: OFF\n"
	"               Fortran Compiler: \n"
	"          Fortran 2003 Compiler: \n"
	"                  Fortran Flags: \n"
	"               H5 Fortran Flags: \n"
	"               AM Fortran Flags: \n"
	"                            C++: OFF\n"
	"                   C++ Compiler: /usr/bin/c++\n"
	"                      C++ Flags:   -fomit-frame-pointer -finline-functions -fno-common -fmessage-length=0\n"
	"                   H5 C++ Flags: \n"
	"                   AM C++ Flags: \n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: OFF\n"
	"             High Level library: ON\n"
	"                   Threadsafety: \n"
	"            Default API Mapping: v110\n"
	" With Deprecated Public Symbols: ON\n"
	"         I/O filters (external): \n"
	"         I/O filters (internal):  SHUFFLE FLETCHER32 NBIT SCALEOFFSET\n"
	"                            MPE: \n"
	"                     Direct VFD: 1\n"
	"                        dmalloc: \n"
	"Clear file buffers before write: ON\n"
	"           Using memory checker: OFF\n"
	"         Function Stack Tracing: OFF\n"
	"      Strict File Format Checks: OFF\n"
	"   Optimization Instrumentation: \n"
	"       Large File Support (LFS): ON\n"
;

