# Generated by CMake 2.8.12.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget hdf5 hdf5_hl)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target hdf5
add_library(hdf5 STATIC IMPORTED)

set_target_properties(hdf5 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/sz/deep/rnnlib_openblas/hdf5/src;/home/sz/deep/rnnlib_openblas/hdf5/src"
)

# Create imported target hdf5_hl
add_library(hdf5_hl STATIC IMPORTED)

set_target_properties(hdf5_hl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/sz/deep/rnnlib_openblas/hdf5/hl/src;/home/sz/deep/rnnlib_openblas/hdf5/hl/src"
)

# Import target "hdf5" for configuration ""
set_property(TARGET hdf5 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(hdf5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "m;dl;dl"
  IMPORTED_LOCATION_NOCONFIG "/home/sz/deep/rnnlib_openblas/hdf5/bin/libhdf5.a"
  )

# Import target "hdf5_hl" for configuration ""
set_property(TARGET hdf5_hl APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(hdf5_hl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "hdf5"
  IMPORTED_LOCATION_NOCONFIG "/home/sz/deep/rnnlib_openblas/hdf5/bin/libhdf5_hl.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
