#ifndef _RNNLIB_FROMSTD_HPP
#define _RNNLIB_FROMSTD_HPP

#include <numeric>
#include <utility>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <string>
#include <sstream>
#include <list>
#include <set>
#include <algorithm>
#include <iterator>
#include <map>
#include <vector>
#include <cmath>
#include <limits>

using std::vector;
using std::map;
using std::string;
using std::set;
using std::ostream;
using std::istream;
using std::numeric_limits;
using std::pair;
using std::cout;
using std::endl;
using std::stringstream;
using std::locale;
using std::negate;
using std::basic_ostream;
using std::basic_istream;
using std::basic_string;
using std::multiplies;
using std::plus;
using std::bind2nd;
using std::minus;
using std::divides;
using std::multimap;
using std::boolalpha;
using std::insert_iterator;
using std::ostringstream;
using std::setw;
using std::setfill;
using std::ifstream;
using std::make_pair;
using std::not_equal_to;
using std::ostream_iterator;
using std::mem_fun_ref;
using std::copy;
using std::min;
using std::max;
using std::inner_product;
using std::fill;
using std::ofstream;
using std::find;
using std::accumulate;
using std::max_element;
using std::swap;
using std::transform;
using std::distance;
using std::abs;
using std::fabs;
using std::floor;
using std::ceil;

#endif
